### ISSUE TITLE
current version on pub.dev (1.2.1) isn't compatible with flutter 3.10

### ISSUE THREAD

**Issue by pedromellofh** [xantiagoma/dart_date#29]
last version of Flutter uses intl 0.18.0, whichs date_dart 1.2.1 doesn't support. the master revision appears to be compatible. when will it be released?

**Comment by josecleiton** [comment]
I have no permission on pub.dev what so ever. Just waiting for @xantiagoma to publish the update

**Comment by bsutton** [comment]
@xantiagoma any update on getting 1.2.2 released?

This is blocking for us.

**Comment by xantiagoma** [comment]
Hi @bsutton @josecleiton @pedromellofh sorry I really haven't had time to work on this due to I'm not using Flutter recently.

A new version was created https://pub.dev/packages/dart_date/versions/1.2.2 also I set up a workflow to automatically publish new versions with a github action (example https://github.com/xantiagoma/dart_date/actions/runs/4998109029/jobs/8953191258) in order to make it work pubspec.yaml should have appropiate version, an entry should be created in CHANGELOG.md and a git tag should be created in repo with semantic versioning: v#.#.#

Let me know if any of you may need access to repo if want to maintain it

**Comment by josecleiton** [comment]
> Hi @bsutton @josecleiton @pedromellofh sorry I really haven't had time to work on this due to I'm not using Flutter recently.
> 
> A new version was created https://pub.dev/packages/dart_date/versions/1.2.2 also I set up a workflow to automatically publish new versions with a github action (example https://github.com/xantiagoma/dart_date/actions/runs/4998109029/jobs/8953191258) in order to make it work pubspec.yaml should have appropiate version, an entry should be created in CHANGELOG.md and a git tag should be created in repo with semantic versioning: v#.#.#
> 
> Let me know if any of you may need access to repo if want to maintain it

I will be happy to help you maintaining this package
